# Generated by Django 2.0 on 2022-12-07 10:54

from django.db import migrations, models
import voting.validators


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='desc',
            field=models.TextField(blank=True, null=True, validators=[voting.validators.lofensivo]),
        ),
    ]
