# Generated by Django 2.0 on 2022-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20221207_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='create_ordination',
            field=models.BooleanField(default=False, verbose_name='Create ordination'),
        ),
        migrations.AddField(
            model_name='question',
            name='tipo',
            field=models.CharField(choices=[('N', 'Normal question'), ('B', 'Binary question')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='voting',
            name='voting_type',
            field=models.CharField(choices=[('N', 'NORMAL VOTING'), ('B', 'BINARY VOTING')], default='N', max_length=2),
        ),
    ]
