# Generated by Django 2.0 on 2022-11-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_binaryquestion_binaryquestionoption_binaryvoting'),
    ]

    operations = [
        migrations.AddField(
            model_name='binaryvoting',
            name='type',
            field=models.CharField(choices=[('BV', 'BinaryVoting')], default='BV', max_length=2),
        ),
    ]
